// GENERATED by gen_bch_decoder.py - do not edit by hand.
// BCH over GF(2^7), reduction 0x09, t=23, n=127.
//
// All three stages wired together and verified end to end by tb_bch_e2e.v. The
// separate area probes this replaces measured a Chien stage that summed only t of
// the t+1 coefficients of the error locator - it left out the constant term, so its
// zero test was not the polynomial's zero test. That is the defect end-to-end
// decoding found and stage-wise synthesis could not.

`default_nettype none

module bch127t23_gf_mul_const #(parameter [6:0] C = 7'h02) (
    input  wire [6:0] a,
    output wire [6:0] y
);
    function [6:0] xtime(input [6:0] v);
        xtime = (v[6]) ? ((v << 1) ^ 7'h09) : (v << 1);
    endfunction
    reg [6:0] acc, cur;
    integer i;
    always @* begin
        acc = 7'h00;
        cur = a;
        for (i = 0; i < 7; i = i + 1) begin
            if (C[i]) acc = acc ^ cur;
            cur = xtime(cur);
        end
    end
    assign y = acc;
endmodule

// S_j <= S_j * alpha^j + bit, fed most significant position first, so that after n
// bits S_j = sum_i b_i alpha^(i*j).
module bch127t23_syndrome_bank (
    input  wire clk,
    input  wire rst_n,
    input  wire load,
    input  wire en,
    input  wire bit_in,
    output wire [7 * 2 * 23 - 1:0] syn
);
    localparam [7 * 46 - 1:0] ALPHAS = {
        7'h1D,7'h4A,7'h25,7'h56,7'h2B,7'h51,7'h6C,7'h36,7'h1B,7'h49,7'h60,7'h30,7'h18,7'h0C,7'h06,7'h03,7'h45,7'h66,7'h33,7'h5D,7'h6A,7'h35,7'h5E,7'h2F,7'h53,7'h6D,7'h72,7'h39,7'h58,7'h2C,7'h16,7'h0B,7'h41,7'h64,7'h32,7'h19,7'h48,7'h24,7'h12,7'h09,7'h40,7'h20,7'h10,7'h08,7'h04,7'h02
    };
    genvar j;
    generate
        for (j = 0; j < 2 * 23; j = j + 1) begin : bank
            reg  [6:0] s;
            wire [6:0] scaled;
            bch127t23_gf_mul_const #(.C(ALPHAS[7*j +: 7])) mc (.a(s), .y(scaled));
            always @(posedge clk) begin
                if (!rst_n || load) s <= 7'h00;
                else if (en)        s <= scaled ^ {{6{1'b0}}, bit_in};
            end
            assign syn[7*j +: 7] = s;
        end
    endgenerate
endmodule

// Chien search over all n positions. Q_k starts at lambda_k and is multiplied by
// alpha^k each cycle, so after c cycles the sum over k is Lambda(alpha^c). The k=0
// term is multiplied by alpha^0 = 1 and needs no multiplier, but it must be in the
// sum - leaving it out is the defect this file was written to remove.
module bch127t23_chien (
    input  wire clk,
    input  wire rst_n,
    input  wire start,
    input  wire en,
    input  wire [7 * (23+1) - 1:0] lambda,
    output wire root
);
    localparam [7 * 24 - 1:0] APOW = {
        7'h2F,7'h53,7'h6D,7'h72,7'h39,7'h58,7'h2C,7'h16,7'h0B,7'h41,7'h64,7'h32,7'h19,7'h48,7'h24,7'h12,7'h09,7'h40,7'h20,7'h10,7'h08,7'h04,7'h02,7'h01
    };
    wire [6:0] q [0:23];
    wire [6:0] chain [0:23];
    genvar k;
    generate
        for (k = 0; k <= 23; k = k + 1) begin : lanes
            reg  [6:0] acc;
            wire [6:0] stepped;
            bch127t23_gf_mul_const #(.C(APOW[7*k +: 7])) mc (.a(acc), .y(stepped));
            always @(posedge clk) begin
                if (!rst_n)     acc <= 7'h00;
                else if (start) acc <= lambda[7*k +: 7];
                else if (en)    acc <= stepped;
            end
            assign q[k] = acc;
        end
        assign chain[0] = q[0];
        for (k = 1; k <= 23; k = k + 1) begin : sum
            assign chain[k] = chain[k-1] ^ q[k];
        end
    endgenerate
    assign root = (chain[23] == 7'h00);
endmodule

// Top: the two table-driven stages. The solver is instantiated by the testbench and
// by the area top, from bm_area_probe.v, because it takes the field as a parameter.
module bch127t23_tables (
    input  wire clk,
    input  wire rst_n,
    input  wire syn_load,
    input  wire syn_en,
    input  wire bit_in,
    input  wire chien_start,
    input  wire chien_en,
    input  wire [7 * (23+1) - 1:0] lambda,
    output wire [7 * 2 * 23 - 1:0] syn,
    output wire root
);
    bch127t23_syndrome_bank sb (
        .clk(clk), .rst_n(rst_n), .load(syn_load), .en(syn_en),
        .bit_in(bit_in), .syn(syn)
    );
    bch127t23_chien cs (
        .clk(clk), .rst_n(rst_n), .start(chien_start), .en(chien_en),
        .lambda(lambda), .root(root)
    );
endmodule

`default_nettype wire
