// GENERATED by gen_bch_decoder.py - do not edit by hand.
// BCH over GF(2^8), reduction 0x1D, t=31, n=255.
//
// All three stages wired together and verified end to end by tb_bch_e2e.v. The
// separate area probes this replaces measured a Chien stage that summed only t of
// the t+1 coefficients of the error locator - it left out the constant term, so its
// zero test was not the polynomial's zero test. That is the defect end-to-end
// decoding found and stage-wise synthesis could not.

`default_nettype none

module bch255t31_gf_mul_const #(parameter [7:0] C = 8'h02) (
    input  wire [7:0] a,
    output wire [7:0] y
);
    function [7:0] xtime(input [7:0] v);
        xtime = (v[7]) ? ((v << 1) ^ 8'h1D) : (v << 1);
    endfunction
    reg [7:0] acc, cur;
    integer i;
    always @* begin
        acc = 8'h00;
        cur = a;
        for (i = 0; i < 8; i = i + 1) begin
            if (C[i]) acc = acc ^ cur;
            cur = xtime(cur);
        end
    end
    assign y = acc;
endmodule

// S_j <= S_j * alpha^j + bit, fed most significant position first, so that after n
// bits S_j = sum_i b_i alpha^(i*j).
module bch255t31_syndrome_bank (
    input  wire clk,
    input  wire rst_n,
    input  wire load,
    input  wire en,
    input  wire bit_in,
    output wire [8 * 2 * 31 - 1:0] syn
);
    localparam [8 * 62 - 1:0] ALPHAS = {
        8'hDE,8'h6F,8'hB9,8'hD2,8'h69,8'hBA,8'h5D,8'hA0,8'h50,8'h28,8'h14,8'h0A,8'h05,8'h8C,8'h46,8'h23,8'h9F,8'hC1,8'hEE,8'h77,8'hB5,8'hD4,8'h6A,8'h35,8'h94,8'h4A,8'h25,8'h9C,8'h4E,8'h27,8'h9D,8'hC0,8'h60,8'h30,8'h18,8'h0C,8'h06,8'h03,8'h8F,8'hC9,8'hEA,8'h75,8'hB4,8'h5A,8'h2D,8'h98,8'h4C,8'h26,8'h13,8'h87,8'hCD,8'hE8,8'h74,8'h3A,8'h1D,8'h80,8'h40,8'h20,8'h10,8'h08,8'h04,8'h02
    };
    genvar j;
    generate
        for (j = 0; j < 2 * 31; j = j + 1) begin : bank
            reg  [7:0] s;
            wire [7:0] scaled;
            bch255t31_gf_mul_const #(.C(ALPHAS[8*j +: 8])) mc (.a(s), .y(scaled));
            always @(posedge clk) begin
                if (!rst_n || load) s <= 8'h00;
                else if (en)        s <= scaled ^ {{7{1'b0}}, bit_in};
            end
            assign syn[8*j +: 8] = s;
        end
    endgenerate
endmodule

// Chien search over all n positions. Q_k starts at lambda_k and is multiplied by
// alpha^k each cycle, so after c cycles the sum over k is Lambda(alpha^c). The k=0
// term is multiplied by alpha^0 = 1 and needs no multiplier, but it must be in the
// sum - leaving it out is the defect this file was written to remove.
module bch255t31_chien (
    input  wire clk,
    input  wire rst_n,
    input  wire start,
    input  wire en,
    input  wire [8 * (31+1) - 1:0] lambda,
    output wire root
);
    localparam [8 * 32 - 1:0] APOW = {
        8'hC0,8'h60,8'h30,8'h18,8'h0C,8'h06,8'h03,8'h8F,8'hC9,8'hEA,8'h75,8'hB4,8'h5A,8'h2D,8'h98,8'h4C,8'h26,8'h13,8'h87,8'hCD,8'hE8,8'h74,8'h3A,8'h1D,8'h80,8'h40,8'h20,8'h10,8'h08,8'h04,8'h02,8'h01
    };
    wire [7:0] q [0:31];
    wire [7:0] chain [0:31];
    genvar k;
    generate
        for (k = 0; k <= 31; k = k + 1) begin : lanes
            reg  [7:0] acc;
            wire [7:0] stepped;
            bch255t31_gf_mul_const #(.C(APOW[8*k +: 8])) mc (.a(acc), .y(stepped));
            always @(posedge clk) begin
                if (!rst_n)     acc <= 8'h00;
                else if (start) acc <= lambda[8*k +: 8];
                else if (en)    acc <= stepped;
            end
            assign q[k] = acc;
        end
        assign chain[0] = q[0];
        for (k = 1; k <= 31; k = k + 1) begin : sum
            assign chain[k] = chain[k-1] ^ q[k];
        end
    endgenerate
    assign root = (chain[31] == 8'h00);
endmodule

// Top: the two table-driven stages. The solver is instantiated by the testbench and
// by the area top, from bm_area_probe.v, because it takes the field as a parameter.
module bch255t31_tables (
    input  wire clk,
    input  wire rst_n,
    input  wire syn_load,
    input  wire syn_en,
    input  wire bit_in,
    input  wire chien_start,
    input  wire chien_en,
    input  wire [8 * (31+1) - 1:0] lambda,
    output wire [8 * 2 * 31 - 1:0] syn,
    output wire root
);
    bch255t31_syndrome_bank sb (
        .clk(clk), .rst_n(rst_n), .load(syn_load), .en(syn_en),
        .bit_in(bit_in), .syn(syn)
    );
    bch255t31_chien cs (
        .clk(clk), .rst_n(rst_n), .start(chien_start), .en(chien_en),
        .lambda(lambda), .root(root)
    );
endmodule

`default_nettype wire
