// GENERATED by gen_bch_decoder.py - do not edit by hand.
// BCH over GF(2^9), reduction 0x11, t=54, n=511.
//
// All three stages wired together and verified end to end by tb_bch_e2e.v. The
// separate area probes this replaces measured a Chien stage that summed only t of
// the t+1 coefficients of the error locator - it left out the constant term, so its
// zero test was not the polynomial's zero test. That is the defect end-to-end
// decoding found and stage-wise synthesis could not.

`default_nettype none

module bch511t54_gf_mul_const #(parameter [8:0] C = 9'h02) (
    input  wire [8:0] a,
    output wire [8:0] y
);
    function [8:0] xtime(input [8:0] v);
        xtime = (v[8]) ? ((v << 1) ^ 9'h11) : (v << 1);
    endfunction
    reg [8:0] acc, cur;
    integer i;
    always @* begin
        acc = 9'h00;
        cur = a;
        for (i = 0; i < 9; i = i + 1) begin
            if (C[i]) acc = acc ^ cur;
            cur = xtime(cur);
        end
    end
    assign y = acc;
endmodule

// S_j <= S_j * alpha^j + bit, fed most significant position first, so that after n
// bits S_j = sum_i b_i alpha^(i*j).
module bch511t54_syndrome_bank (
    input  wire clk,
    input  wire rst_n,
    input  wire load,
    input  wire en,
    input  wire bit_in,
    output wire [9 * 2 * 54 - 1:0] syn
);
    localparam [9 * 108 - 1:0] ALPHAS = {
        9'h1C7,9'h1EB,9'h1FD,9'h1F6,9'hFB,9'h175,9'h1B2,9'hD9,9'h164,9'hB2,9'h59,9'h124,9'h92,9'h49,9'h12C,9'h96,9'h4B,9'h12D,9'h19E,9'hCF,9'h16F,9'h1BF,9'h1D7,9'h1E3,9'h1F9,9'h1F4,9'hFA,9'h7D,9'h136,9'h9B,9'h145,9'h1AA,9'hD5,9'h162,9'hB1,9'h150,9'hA8,9'h54,9'h2A,9'h15,9'h102,9'h81,9'h148,9'hA4,9'h52,9'h29,9'h11C,9'h8E,9'h47,9'h12B,9'h19D,9'h1C6,9'hE3,9'h179,9'h1B4,9'hDA,9'h6D,9'h13E,9'h9F,9'h147,9'h1AB,9'h1DD,9'h1E6,9'hF3,9'h171,9'h1B0,9'hD8,9'h6C,9'h36,9'h1B,9'h105,9'h18A,9'hC5,9'h16A,9'hB5,9'h152,9'hA9,9'h15C,9'hAE,9'h57,9'h123,9'h199,9'h1C4,9'hE2,9'h71,9'h130,9'h98,9'h4C,9'h26,9'h13,9'h101,9'h188,9'hC4,9'h62,9'h31,9'h110,9'h88,9'h44,9'h22,9'h11,9'h100,9'h80,9'h40,9'h20,9'h10,9'h08,9'h04,9'h02
    };
    genvar j;
    generate
        for (j = 0; j < 2 * 54; j = j + 1) begin : bank
            reg  [8:0] s;
            wire [8:0] scaled;
            bch511t54_gf_mul_const #(.C(ALPHAS[9*j +: 9])) mc (.a(s), .y(scaled));
            always @(posedge clk) begin
                if (!rst_n || load) s <= 9'h00;
                else if (en)        s <= scaled ^ {{8{1'b0}}, bit_in};
            end
            assign syn[9*j +: 9] = s;
        end
    endgenerate
endmodule

// Chien search over all n positions. Q_k starts at lambda_k and is multiplied by
// alpha^k each cycle, so after c cycles the sum over k is Lambda(alpha^c). The k=0
// term is multiplied by alpha^0 = 1 and needs no multiplier, but it must be in the
// sum - leaving it out is the defect this file was written to remove.
module bch511t54_chien (
    input  wire clk,
    input  wire rst_n,
    input  wire start,
    input  wire en,
    input  wire [9 * (54+1) - 1:0] lambda,
    output wire root
);
    localparam [9 * 55 - 1:0] APOW = {
        9'h1B4,9'hDA,9'h6D,9'h13E,9'h9F,9'h147,9'h1AB,9'h1DD,9'h1E6,9'hF3,9'h171,9'h1B0,9'hD8,9'h6C,9'h36,9'h1B,9'h105,9'h18A,9'hC5,9'h16A,9'hB5,9'h152,9'hA9,9'h15C,9'hAE,9'h57,9'h123,9'h199,9'h1C4,9'hE2,9'h71,9'h130,9'h98,9'h4C,9'h26,9'h13,9'h101,9'h188,9'hC4,9'h62,9'h31,9'h110,9'h88,9'h44,9'h22,9'h11,9'h100,9'h80,9'h40,9'h20,9'h10,9'h08,9'h04,9'h02,9'h01
    };
    wire [8:0] q [0:54];
    wire [8:0] chain [0:54];
    genvar k;
    generate
        for (k = 0; k <= 54; k = k + 1) begin : lanes
            reg  [8:0] acc;
            wire [8:0] stepped;
            bch511t54_gf_mul_const #(.C(APOW[9*k +: 9])) mc (.a(acc), .y(stepped));
            always @(posedge clk) begin
                if (!rst_n)     acc <= 9'h00;
                else if (start) acc <= lambda[9*k +: 9];
                else if (en)    acc <= stepped;
            end
            assign q[k] = acc;
        end
        assign chain[0] = q[0];
        for (k = 1; k <= 54; k = k + 1) begin : sum
            assign chain[k] = chain[k-1] ^ q[k];
        end
    endgenerate
    assign root = (chain[54] == 9'h00);
endmodule

// Top: the two table-driven stages. The solver is instantiated by the testbench and
// by the area top, from bm_area_probe.v, because it takes the field as a parameter.
module bch511t54_tables (
    input  wire clk,
    input  wire rst_n,
    input  wire syn_load,
    input  wire syn_en,
    input  wire bit_in,
    input  wire chien_start,
    input  wire chien_en,
    input  wire [9 * (54+1) - 1:0] lambda,
    output wire [9 * 2 * 54 - 1:0] syn,
    output wire root
);
    bch511t54_syndrome_bank sb (
        .clk(clk), .rst_n(rst_n), .load(syn_load), .en(syn_en),
        .bit_in(bit_in), .syn(syn)
    );
    bch511t54_chien cs (
        .clk(clk), .rst_n(rst_n), .start(chien_start), .en(chien_en),
        .lambda(lambda), .root(root)
    );
endmodule

`default_nettype wire
