#!/usr/bin/env python3
"""Emit the SLLC systematic encoder for a given BCH code, and a reference for testing it.

sllc_stages.v was written by hand for BCH(127,29,21) - a degree-98 generator, forty-nine
taps typed out one per line - and carried into every budget since, including the ones
built on BCH(127,57,11), whose generator has degree 70. The area was quoted for a
circuit that encodes the wrong code, and there was no testbench, so a wrong tap would
have been invisible in both directions.

This computes the generator polynomial from the code parameters the same way
gen_bch_decoder.py computes its constants - from cyclotomic cosets - and emits the
shift register for it. The taps are then a consequence of the code rather than a
transcription of it.

Usage: gen_sllc.py <m> <reduction> <t> <name>   (same argument order as the decoder)
"""

import sys


def minimal_polynomials(m, red, t):
    """Generator polynomial of the narrow-sense BCH code, as a bit mask, low bit = x^0."""
    n = (1 << m) - 1
    mask = n

    def mul(a, b):
        acc = 0
        for i in range(m):
            if (b >> i) & 1:
                acc ^= a
            a = ((a << 1) ^ red) & mask if (a >> (m - 1)) & 1 else (a << 1) & mask
        return acc

    # cyclotomic cosets of 1..2t, each giving one minimal polynomial
    cosets, seen = [], set()
    for s in range(1, 2 * t + 1):
        if s in seen:
            continue
        c, x = [], s
        while x not in c:
            c.append(x)
            seen.add(x)
            x = (2 * x) % n
        cosets.append(c)

    # alpha^i as a field element, then prod (x - alpha^e) over the coset
    alpha_pow = [1] * n
    for i in range(1, n):
        alpha_pow[i] = mul(alpha_pow[i - 1], 2)

    g = 1
    for c in cosets:
        poly = [1]                       # coefficients in GF(2^m), ascending powers of x
        for e in c:
            root = alpha_pow[e % n]
            new = [0] * (len(poly) + 1)
            for i, co in enumerate(poly):
                new[i + 1] ^= co         # x * poly
                new[i] ^= mul(co, root)  # root * poly
            poly = new
        assert all(co in (0, 1) for co in poly), "minimal polynomial left the base field"
        mp = 0
        for i, co in enumerate(poly):
            if co:
                mp |= 1 << i
        # multiply g by mp over GF(2)
        acc = 0
        for i in range(mp.bit_length()):
            if (mp >> i) & 1:
                acc ^= g << i
        g = acc
    return g


def emit(m, red, t, name):
    n = (1 << m) - 1
    g = minimal_polynomials(m, red, t)
    deg = g.bit_length() - 1
    k = n - deg
    taps = [i for i in range(deg) if (g >> i) & 1]

    lines = []
    for i in taps:
        if i == 0:
            continue
        # A zero-width part is a syntax error, not a no-op, so the top tap is a special
        # case rather than a general formula with a degenerate arm.
        term = (f"{{fb, {i}'b0}}" if i == deg - 1
                else f"{{{deg-1-i}'b0, fb, {i}'b0}}")
        lines.append(f"                | ({term})   // g[{i}]")
    body = "\n".join(lines)

    return f"""// GENERATED by gen_sllc.py - do not edit by hand.
// Systematic Low Leakage Coding stages for BCH({n},{k},{t}) over GF(2^{m}).
//
// Enrolment computes the systematic redundancy - the remainder of the information part
// times x^(n-k) modulo the generator - with a shift register of degree {deg}, then
// exclusive-ors it with fresh response bits to form the helper data. Reconstruction only
// exclusive-ors the helper data with the noisy mask, which is the whole on-device cost
// when enrolment happens off the die.
//
// The taps come from the generator polynomial computed from the cyclotomic cosets of
// alpha^1..alpha^{2*t}, not from transcription. tb_sllc.v checks the register against a
// software polynomial division before any area is quoted for it.

`default_nettype none

module {name}_encoder (
    input  wire clk,
    input  wire rst_n,
    input  wire en,          // shift one information bit in, most significant first
    input  wire bit_in,
    output wire [{deg-1}:0] parity
);
    reg [{deg-1}:0] reg_lfsr;
    wire fb = bit_in ^ reg_lfsr[{deg-1}];
    always @(posedge clk) begin
        if (!rst_n) reg_lfsr <= {deg}'b0;
        else if (en) begin
            reg_lfsr <= {{reg_lfsr[{deg-2}:0], 1'b0}} ^ ({deg}'b0
{body}
                | {{{deg-1}'b0, fb}});
        end
    end
    assign parity = reg_lfsr;
endmodule

// Reconstruction side: the helper data is unmasked with the noisy response bits.
module {name}_unmask (
    input  wire [{deg-1}:0] helper,
    input  wire [{deg-1}:0] mask_noisy,
    output wire [{deg-1}:0] redundancy
);
    assign redundancy = helper ^ mask_noisy;
endmodule

`default_nettype wire
"""


def reference_parity(g, deg, bits):
    """Remainder of the information word times x^deg modulo g, over GF(2)."""
    reg = 0
    for b in bits:
        fb = b ^ ((reg >> (deg - 1)) & 1)
        reg = ((reg << 1) & ((1 << deg) - 1))
        if fb:
            reg ^= g & ((1 << deg) - 1)
    return reg


def emit_tb(m, red, t, name, count=24):
    """A self-contained testbench: the register against a software polynomial division.

    The vectors are computed here and baked in, so the testbench needs no file IO and
    the reference cannot silently become the circuit's own output.
    """
    import random

    g = minimal_polynomials(m, red, t)
    deg = g.bit_length() - 1
    k = (1 << m) - 1 - deg
    rng = random.Random(20260731)
    vectors = []
    for _ in range(count):
        bits = [rng.randint(0, 1) for _ in range(k)]
        word = 0
        for b in bits:
            word = (word << 1) | b
        vectors.append((word, reference_parity(g, deg, bits)))

    rows = "\n".join(
        f"        words[{i}] = {k}'h{w:0{(k+3)//4}x}; "
        f"want[{i}] = {deg}'h{p:0{(deg+3)//4}x};"
        for i, (w, p) in enumerate(vectors))

    return f"""// GENERATED by gen_sllc.py --tb - do not edit by hand.
//
// The SLLC encoder's area was quoted for five loops with no testbench behind it, in a
// project whose rule is that no area is quoted for a circuit that has not been
// exercised. The register is checked here against a software polynomial division over
// GF(2), on {count} random information words, and an injected fault must fail it.

`timescale 1ns/1ps
`default_nettype none

module tb_sllc;
    localparam K = {k}, DEG = {deg};
    reg clk = 0, rst_n = 0, en = 0, bit_in = 0;
    wire [DEG-1:0] parity;

    {name}_encoder dut (.clk(clk), .rst_n(rst_n), .en(en), .bit_in(bit_in),
                        .parity(parity));

    always #5 clk = ~clk;

    reg [K-1:0]   words  [0:{count-1}];
    reg [DEG-1:0] want   [0:{count-1}];   // not `expect`, which is a keyword
    integer v, b, bad;

    // The unmask stage is a bare exclusive-or, so it is checked by identity rather than
    // by vector: unmasking with the same mask must return the redundancy.
    reg  [DEG-1:0] red_in, mask;
    wire [DEG-1:0] helper, back;
    {name}_unmask mk (.helper(red_in), .mask_noisy(mask), .redundancy(helper));
    {name}_unmask um (.helper(helper), .mask_noisy(mask), .redundancy(back));

    initial begin
{rows}
        bad = 0;
        for (v = 0; v < {count}; v = v + 1) begin
            @(negedge clk); rst_n = 0; en = 0;
            @(negedge clk); rst_n = 1;
            for (b = K - 1; b >= 0; b = b - 1) begin
                bit_in = words[v][b];
                en = 1;
                @(negedge clk);
            end
            en = 0;
            if (parity !== want[v]) begin
                bad = bad + 1;
                $display("MISMATCH vector %0d: got %h want %h", v, parity, want[v]);
            end
        end

        red_in = {{DEG{{1'b0}}}} | 70'h2a5f13c8b90d4e7;
        mask   = {{DEG{{1'b0}}}} | 70'h13f0c5a29e6b8d1;
        #1;
        if (back !== red_in) begin
            bad = bad + 1;
            $display("MISMATCH unmask round trip: got %h want %h", back, red_in);
        end

        if (bad == 0)
            $display("PASS sllc encoder matches polynomial division on {count} words");
        else
            $display("FAIL %0d of {count+1} checks", bad);
        $finish;
    end
endmodule

`default_nettype wire
"""


if __name__ == "__main__":
    m, red, t, name = int(sys.argv[1]), int(sys.argv[2], 0), int(sys.argv[3]), sys.argv[4]
    if "--tb" in sys.argv:
        sys.stdout.write(emit_tb(m, red, t, name))
    elif "--vectors" in sys.argv:
        # Test vectors for tb_sllc.v: information word, expected parity. Written as hex
        # so the testbench reads them without a parser.
        import random
        g = minimal_polynomials(m, red, t)
        deg = g.bit_length() - 1
        k = (1 << m) - 1 - deg
        rng = random.Random(20260731)
        for _ in range(24):
            bits = [rng.randint(0, 1) for _ in range(k)]
            word = 0
            for b in bits:
                word = (word << 1) | b
            print(f"{word:0{(k+3)//4}x} {reference_parity(g, deg, bits):0{(deg+3)//4}x}")
    else:
        sys.stdout.write(emit(m, red, t, name))
