#!/usr/bin/env python3
"""Emit a complete BCH decoder for a given field and correction strength, so that
the three stages can be verified together rather than measured apart.

Why this exists. bch_area_probe.v measured a syndrome bank and a Chien search and
called them structural area probes, which was honest about their status and turned
out to matter: wiring them to the solver and decoding through them showed the Chien
stage summed only t of the t+1 coefficients of the error locator. It omitted the
constant term, so its zero test was not the polynomial's zero test. An area figure
had been quoted for that circuit.

Tables rather than parameters, because the syndrome and Chien stages multiply by
compile-time constants - which is what makes them cheap - and those constants are
field facts. The solver needs none of this: every multiply in it is general, so it
takes the field as a parameter and lives in bm_area_probe.v.
"""

import sys


def field(m, red):
    """Multiplication and powers in GF(2^m) with the given reduction polynomial."""
    mask = (1 << m) - 1

    def mul(a, b):
        acc = 0
        for i in range(m):
            if (b >> i) & 1:
                acc ^= a
            a = ((a << 1) ^ red) & mask if (a >> (m - 1)) & 1 else (a << 1) & mask
        return acc

    def power(a, e):
        r = 1
        for _ in range(e):
            r = mul(r, a)
        return r

    return mul, power


def emit(m, red, t, name):
    mul, power = field(m, red)
    n = (1 << m) - 1
    alphas = [power(2, j) for j in range(1, 2 * t + 1)]       # syndrome constants
    apow = [power(2, k) for k in range(0, t + 1)]             # Chien constants, k=0..t

    def lit(vals):
        return ",".join(f"{m}'h{v:02X}" for v in reversed(vals))

    return f"""// GENERATED by gen_bch_decoder.py - do not edit by hand.
// BCH over GF(2^{m}), reduction 0x{red:02X}, t={t}, n={n}.
//
// All three stages wired together and verified end to end by tb_bch_e2e.v. The
// separate area probes this replaces measured a Chien stage that summed only t of
// the t+1 coefficients of the error locator - it left out the constant term, so its
// zero test was not the polynomial's zero test. That is the defect end-to-end
// decoding found and stage-wise synthesis could not.

`default_nettype none

module {name}_gf_mul_const #(parameter [{m-1}:0] C = {m}'h02) (
    input  wire [{m-1}:0] a,
    output wire [{m-1}:0] y
);
    function [{m-1}:0] xtime(input [{m-1}:0] v);
        xtime = (v[{m-1}]) ? ((v << 1) ^ {m}'h{red:02X}) : (v << 1);
    endfunction
    reg [{m-1}:0] acc, cur;
    integer i;
    always @* begin
        acc = {m}'h00;
        cur = a;
        for (i = 0; i < {m}; i = i + 1) begin
            if (C[i]) acc = acc ^ cur;
            cur = xtime(cur);
        end
    end
    assign y = acc;
endmodule

// S_j <= S_j * alpha^j + bit, fed most significant position first, so that after n
// bits S_j = sum_i b_i alpha^(i*j).
module {name}_syndrome_bank (
    input  wire clk,
    input  wire rst_n,
    input  wire load,
    input  wire en,
    input  wire bit_in,
    output wire [{m} * 2 * {t} - 1:0] syn
);
    localparam [{m} * {2*t} - 1:0] ALPHAS = {{
        {lit(alphas)}
    }};
    genvar j;
    generate
        for (j = 0; j < 2 * {t}; j = j + 1) begin : bank
            reg  [{m-1}:0] s;
            wire [{m-1}:0] scaled;
            {name}_gf_mul_const #(.C(ALPHAS[{m}*j +: {m}])) mc (.a(s), .y(scaled));
            always @(posedge clk) begin
                if (!rst_n || load) s <= {m}'h00;
                else if (en)        s <= scaled ^ {{{{{m-1}{{1'b0}}}}, bit_in}};
            end
            assign syn[{m}*j +: {m}] = s;
        end
    endgenerate
endmodule

// Chien search over all n positions. Q_k starts at lambda_k and is multiplied by
// alpha^k each cycle, so after c cycles the sum over k is Lambda(alpha^c). The k=0
// term is multiplied by alpha^0 = 1 and needs no multiplier, but it must be in the
// sum - leaving it out is the defect this file was written to remove.
module {name}_chien (
    input  wire clk,
    input  wire rst_n,
    input  wire start,
    input  wire en,
    input  wire [{m} * ({t}+1) - 1:0] lambda,
    output wire root
);
    localparam [{m} * {t+1} - 1:0] APOW = {{
        {lit(apow)}
    }};
    wire [{m-1}:0] q [0:{t}];
    wire [{m-1}:0] chain [0:{t}];
    genvar k;
    generate
        for (k = 0; k <= {t}; k = k + 1) begin : lanes
            reg  [{m-1}:0] acc;
            wire [{m-1}:0] stepped;
            {name}_gf_mul_const #(.C(APOW[{m}*k +: {m}])) mc (.a(acc), .y(stepped));
            always @(posedge clk) begin
                if (!rst_n)     acc <= {m}'h00;
                else if (start) acc <= lambda[{m}*k +: {m}];
                else if (en)    acc <= stepped;
            end
            assign q[k] = acc;
        end
        assign chain[0] = q[0];
        for (k = 1; k <= {t}; k = k + 1) begin : sum
            assign chain[k] = chain[k-1] ^ q[k];
        end
    endgenerate
    assign root = (chain[{t}] == {m}'h00);
endmodule

// Top: the two table-driven stages. The solver is instantiated by the testbench and
// by the area top, from bm_area_probe.v, because it takes the field as a parameter.
module {name}_tables (
    input  wire clk,
    input  wire rst_n,
    input  wire syn_load,
    input  wire syn_en,
    input  wire bit_in,
    input  wire chien_start,
    input  wire chien_en,
    input  wire [{m} * ({t}+1) - 1:0] lambda,
    output wire [{m} * 2 * {t} - 1:0] syn,
    output wire root
);
    {name}_syndrome_bank sb (
        .clk(clk), .rst_n(rst_n), .load(syn_load), .en(syn_en),
        .bit_in(bit_in), .syn(syn)
    );
    {name}_chien cs (
        .clk(clk), .rst_n(rst_n), .start(chien_start), .en(chien_en),
        .lambda(lambda), .root(root)
    );
endmodule

`default_nettype wire
"""


if __name__ == "__main__":
    m, red, t, name = int(sys.argv[1]), int(sys.argv[2], 0), int(sys.argv[3]), sys.argv[4]
    sys.stdout.write(emit(m, red, t, name))
