// GENERATED by gen_sllc.py - do not edit by hand.
// Systematic Low Leakage Coding stages for BCH(127,78,7) over GF(2^7).
//
// Enrolment computes the systematic redundancy - the remainder of the information part
// times x^(n-k) modulo the generator - with a shift register of degree 49, then
// exclusive-ors it with fresh response bits to form the helper data. Reconstruction only
// exclusive-ors the helper data with the noisy mask, which is the whole on-device cost
// when enrolment happens off the die.
//
// The taps come from the generator polynomial computed from the cyclotomic cosets of
// alpha^1..alpha^14, not from transcription. tb_sllc.v checks the register against a
// software polynomial division before any area is quoted for it.

`default_nettype none

module sllc127t7_encoder (
    input  wire clk,
    input  wire rst_n,
    input  wire en,          // shift one information bit in, most significant first
    input  wire bit_in,
    output wire [48:0] parity
);
    reg [48:0] reg_lfsr;
    wire fb = bit_in ^ reg_lfsr[48];
    always @(posedge clk) begin
        if (!rst_n) reg_lfsr <= 49'b0;
        else if (en) begin
            reg_lfsr <= {reg_lfsr[47:0], 1'b0} ^ (49'b0
                | ({46'b0, fb, 2'b0})   // g[2]
                | ({45'b0, fb, 3'b0})   // g[3]
                | ({42'b0, fb, 6'b0})   // g[6]
                | ({36'b0, fb, 12'b0})   // g[12]
                | ({35'b0, fb, 13'b0})   // g[13]
                | ({33'b0, fb, 15'b0})   // g[15]
                | ({29'b0, fb, 19'b0})   // g[19]
                | ({28'b0, fb, 20'b0})   // g[20]
                | ({26'b0, fb, 22'b0})   // g[22]
                | ({25'b0, fb, 23'b0})   // g[23]
                | ({24'b0, fb, 24'b0})   // g[24]
                | ({20'b0, fb, 28'b0})   // g[28]
                | ({9'b0, fb, 39'b0})   // g[39]
                | ({8'b0, fb, 40'b0})   // g[40]
                | ({5'b0, fb, 43'b0})   // g[43]
                | ({2'b0, fb, 46'b0})   // g[46]
                | ({1'b0, fb, 47'b0})   // g[47]
                | {48'b0, fb});
        end
    end
    assign parity = reg_lfsr;
endmodule

// Reconstruction side: the helper data is unmasked with the noisy response bits.
module sllc127t7_unmask (
    input  wire [48:0] helper,
    input  wire [48:0] mask_noisy,
    output wire [48:0] redundancy
);
    assign redundancy = helper ^ mask_noisy;
endmodule

`default_nettype wire
