// GENERATED by gen_sllc.py - do not edit by hand.
// Systematic Low Leakage Coding stages for BCH(127,57,11) over GF(2^7).
//
// Enrolment computes the systematic redundancy - the remainder of the information part
// times x^(n-k) modulo the generator - with a shift register of degree 70, then
// exclusive-ors it with fresh response bits to form the helper data. Reconstruction only
// exclusive-ors the helper data with the noisy mask, which is the whole on-device cost
// when enrolment happens off the die.
//
// The taps come from the generator polynomial computed from the cyclotomic cosets of
// alpha^1..alpha^22, not from transcription. tb_sllc.v checks the register against a
// software polynomial division before any area is quoted for it.

`default_nettype none

module sllc127t11_encoder (
    input  wire clk,
    input  wire rst_n,
    input  wire en,          // shift one information bit in, most significant first
    input  wire bit_in,
    output wire [69:0] parity
);
    reg [69:0] reg_lfsr;
    wire fb = bit_in ^ reg_lfsr[69];
    always @(posedge clk) begin
        if (!rst_n) reg_lfsr <= 70'b0;
        else if (en) begin
            reg_lfsr <= {reg_lfsr[68:0], 1'b0} ^ (70'b0
                | ({65'b0, fb, 4'b0})   // g[4]
                | ({63'b0, fb, 6'b0})   // g[6]
                | ({62'b0, fb, 7'b0})   // g[7]
                | ({61'b0, fb, 8'b0})   // g[8]
                | ({60'b0, fb, 9'b0})   // g[9]
                | ({59'b0, fb, 10'b0})   // g[10]
                | ({58'b0, fb, 11'b0})   // g[11]
                | ({57'b0, fb, 12'b0})   // g[12]
                | ({54'b0, fb, 15'b0})   // g[15]
                | ({52'b0, fb, 17'b0})   // g[17]
                | ({51'b0, fb, 18'b0})   // g[18]
                | ({50'b0, fb, 19'b0})   // g[19]
                | ({48'b0, fb, 21'b0})   // g[21]
                | ({46'b0, fb, 23'b0})   // g[23]
                | ({42'b0, fb, 27'b0})   // g[27]
                | ({40'b0, fb, 29'b0})   // g[29]
                | ({36'b0, fb, 33'b0})   // g[33]
                | ({35'b0, fb, 34'b0})   // g[34]
                | ({34'b0, fb, 35'b0})   // g[35]
                | ({33'b0, fb, 36'b0})   // g[36]
                | ({31'b0, fb, 38'b0})   // g[38]
                | ({27'b0, fb, 42'b0})   // g[42]
                | ({25'b0, fb, 44'b0})   // g[44]
                | ({23'b0, fb, 46'b0})   // g[46]
                | ({21'b0, fb, 48'b0})   // g[48]
                | ({19'b0, fb, 50'b0})   // g[50]
                | ({17'b0, fb, 52'b0})   // g[52]
                | ({15'b0, fb, 54'b0})   // g[54]
                | ({13'b0, fb, 56'b0})   // g[56]
                | ({11'b0, fb, 58'b0})   // g[58]
                | ({10'b0, fb, 59'b0})   // g[59]
                | ({8'b0, fb, 61'b0})   // g[61]
                | ({6'b0, fb, 63'b0})   // g[63]
                | ({4'b0, fb, 65'b0})   // g[65]
                | ({3'b0, fb, 66'b0})   // g[66]
                | ({2'b0, fb, 67'b0})   // g[67]
                | ({fb, 69'b0})   // g[69]
                | {69'b0, fb});
        end
    end
    assign parity = reg_lfsr;
endmodule

// Reconstruction side: the helper data is unmasked with the noisy response bits.
module sllc127t11_unmask (
    input  wire [69:0] helper,
    input  wire [69:0] mask_noisy,
    output wire [69:0] redundancy
);
    assign redundancy = helper ^ mask_noisy;
endmodule

`default_nettype wire
