// GENERATED by gen_sllc.py --tb - do not edit by hand.
//
// The SLLC encoder's area was quoted for five loops with no testbench behind it, in a
// project whose rule is that no area is quoted for a circuit that has not been
// exercised. The register is checked here against a software polynomial division over
// GF(2), on 24 random information words, and an injected fault must fail it.

`timescale 1ns/1ps
`default_nettype none

module tb_sllc;
    localparam K = 78, DEG = 49;
    reg clk = 0, rst_n = 0, en = 0, bit_in = 0;
    wire [DEG-1:0] parity;

    sllc127t7_encoder dut (.clk(clk), .rst_n(rst_n), .en(en), .bit_in(bit_in),
                        .parity(parity));

    always #5 clk = ~clk;

    reg [K-1:0]   words  [0:23];
    reg [DEG-1:0] want   [0:23];   // not `expect`, which is a keyword
    integer v, b, bad;

    // The unmask stage is a bare exclusive-or, so it is checked by identity rather than
    // by vector: unmasking with the same mask must return the redundancy.
    reg  [DEG-1:0] red_in, mask;
    wire [DEG-1:0] helper, back;
    sllc127t7_unmask mk (.helper(red_in), .mask_noisy(mask), .redundancy(helper));
    sllc127t7_unmask um (.helper(helper), .mask_noisy(mask), .redundancy(back));

    initial begin
        words[0] = 78'h1151cd4b998cd32c3045; want[0] = 49'h0d5ac011dd9db;
        words[1] = 78'h3a955e82e4e4cd53d4d9; want[1] = 49'h0953b3ea1d6e0;
        words[2] = 78'h12a923751abd7150ea24; want[2] = 49'h10317c382a4cb;
        words[3] = 78'h3730d014c152317e9891; want[3] = 49'h167f233571fcc;
        words[4] = 78'h24319a9c06d1fca573da; want[4] = 49'h0862319341e25;
        words[5] = 78'h3b924f76d4a6cce76d1a; want[5] = 49'h1d2ea60100db4;
        words[6] = 78'h11d3794cb3337959c539; want[6] = 49'h035b235491253;
        words[7] = 78'h0b52e9d4c501952b68ae; want[7] = 49'h094310446fb29;
        words[8] = 78'h226e9a1f1f35b5559b91; want[8] = 49'h0e955305138b5;
        words[9] = 78'h0407977061290619e6b4; want[9] = 49'h03f6d893dcb26;
        words[10] = 78'h05a6b08268c7c5144df6; want[10] = 49'h10fcf09b2d571;
        words[11] = 78'h18f424457318aa900960; want[11] = 49'h1fd07276ecfc9;
        words[12] = 78'h0a043f3c7c59768204e3; want[12] = 49'h0ec015017c930;
        words[13] = 78'h21e170eb330fa2e45263; want[13] = 49'h00b3c4851427c;
        words[14] = 78'h2874d71e05e62042b194; want[14] = 49'h0992e7bdcdf04;
        words[15] = 78'h3d74009a679c8a73b208; want[15] = 49'h198d9f2108071;
        words[16] = 78'h3180a8ef0791e53082a6; want[16] = 49'h187055591c2dc;
        words[17] = 78'h16127818cef34c9db718; want[17] = 49'h1b59d2f96962e;
        words[18] = 78'h1d5b19182f619a220098; want[18] = 49'h0df3fae355469;
        words[19] = 78'h1efec6023fbfac16cf14; want[19] = 49'h1568d1c566246;
        words[20] = 78'h3a907941273951f70b57; want[20] = 49'h1d1db7e75c0d8;
        words[21] = 78'h1a8d313edd7482ba6754; want[21] = 49'h1d6537311f9da;
        words[22] = 78'h00b0cb8510ae2e0b69f0; want[22] = 49'h1a9bb0c6c2db2;
        words[23] = 78'h0efaccf0e5db5ed5b8b6; want[23] = 49'h0cb38214e7030;
        bad = 0;
        for (v = 0; v < 24; v = v + 1) begin
            @(negedge clk); rst_n = 0; en = 0;
            @(negedge clk); rst_n = 1;
            for (b = K - 1; b >= 0; b = b - 1) begin
                bit_in = words[v][b];
                en = 1;
                @(negedge clk);
            end
            en = 0;
            if (parity !== want[v]) begin
                bad = bad + 1;
                $display("MISMATCH vector %0d: got %h want %h", v, parity, want[v]);
            end
        end

        red_in = {DEG{1'b0}} | 70'h2a5f13c8b90d4e7;
        mask   = {DEG{1'b0}} | 70'h13f0c5a29e6b8d1;
        #1;
        if (back !== red_in) begin
            bad = bad + 1;
            $display("MISMATCH unmask round trip: got %h want %h", back, red_in);
        end

        if (bad == 0)
            $display("PASS sllc encoder matches polynomial division on 24 words");
        else
            $display("FAIL %0d of 25 checks", bad);
        $finish;
    end
endmodule

`default_nettype wire
