// GENERATED by gen_sllc.py --tb - do not edit by hand.
//
// The SLLC encoder's area was quoted for five loops with no testbench behind it, in a
// project whose rule is that no area is quoted for a circuit that has not been
// exercised. The register is checked here against a software polynomial division over
// GF(2), on 24 random information words, and an injected fault must fail it.

`timescale 1ns/1ps
`default_nettype none

module tb_sllc;
    localparam K = 57, DEG = 70;
    reg clk = 0, rst_n = 0, en = 0, bit_in = 0;
    wire [DEG-1:0] parity;

    sllc127t11_encoder dut (.clk(clk), .rst_n(rst_n), .en(en), .bit_in(bit_in),
                        .parity(parity));

    always #5 clk = ~clk;

    reg [K-1:0]   words  [0:23];
    reg [DEG-1:0] want   [0:23];   // not `expect`, which is a keyword
    integer v, b, bad;

    // The unmask stage is a bare exclusive-or, so it is checked by identity rather than
    // by vector: unmasking with the same mask must return the redundancy.
    reg  [DEG-1:0] red_in, mask;
    wire [DEG-1:0] helper, back;
    sllc127t11_unmask mk (.helper(red_in), .mask_noisy(mask), .redundancy(helper));
    sllc127t11_unmask um (.helper(helper), .mask_noisy(mask), .redundancy(back));

    initial begin
        words[0] = 57'h08a8e6a5ccc6699; want[0] = 70'h3e069036bb07be1675;
        words[1] = 57'h0c3045ea557a0b9; want[1] = 70'h12c246a073043c2bdc;
        words[2] = 57'h07266a9ea6ca552; want[2] = 70'h105ade3b6fcc0bf11f;
        words[3] = 57'h08dd46af5c543a8; want[3] = 70'h3f7b9f02556d8e996a;
        words[4] = 57'h126e61a02982a46; want[4] = 70'h231db832fc55512e98;
        words[5] = 57'h05fa62464319a9c; want[5] = 70'h11ee7c091efc29db51;
        words[6] = 57'h00da3f94ae7b5dc; want[6] = 70'h038403076246ad5dd0;
        words[7] = 57'h124f76d4a6cce76; want[7] = 70'h1234563b5853a2c3cc;
        words[8] = 57'h1a348e9bca65999; want[8] = 70'h19380b4725834d5b48;
        words[9] = 57'h17959c5392d4ba7; want[9] = 70'h3eca117276f6f7d609;
        words[10] = 57'h0a6280ca95b4574; want[10] = 70'h13cee0bd6f16137720;
        words[11] = 57'h09ba687c7cd6d55; want[11] = 70'h2f1e4e83007c913c55;
        words[12] = 57'h0cdc8880f2ee0c2; want[12] = 70'h106e483b54065f716a;
        words[13] = 57'h0a418679ad05a6b; want[13] = 70'h38b6d9f979a6f8617a;
        words[14] = 57'h0104d18f8a289be; want[14] = 70'h39fda21b367a7bca62;
        words[15] = 57'h198f424457318aa; want[15] = 70'h3638305ddd27bcdbc5;
        words[16] = 57'h12012c05021f9e3; want[16] = 70'h122111ea162c6afa2c;
        words[17] = 57'h1c59768204e3878; want[17] = 70'h266118add7b7ce7b9f;
        words[18] = 57'h0b8759987d17229; want[18] = 70'h19f60ee1c641e6d2a5;
        words[19] = 57'h063a1d35c781798; want[19] = 70'h2bd75a62bfb7e2eac7;
        words[20] = 57'h102158ca7ae8013; want[20] = 70'h34ddd80efdb3ff2259;
        words[21] = 57'h099e7229cec8231; want[21] = 70'h3ec426681c6c0e5680;
        words[22] = 57'h10151de0f23ca61; want[22] = 70'h0c01e0efa5430dd1ac;
        words[23] = 57'h00a996127818cef; want[23] = 70'h0d2ebfb6bb4b35e4ed;
        bad = 0;
        for (v = 0; v < 24; v = v + 1) begin
            @(negedge clk); rst_n = 0; en = 0;
            @(negedge clk); rst_n = 1;
            for (b = K - 1; b >= 0; b = b - 1) begin
                bit_in = words[v][b];
                en = 1;
                @(negedge clk);
            end
            en = 0;
            if (parity !== want[v]) begin
                bad = bad + 1;
                $display("MISMATCH vector %0d: got %h want %h", v, parity, want[v]);
            end
        end

        red_in = {DEG{1'b0}} | 70'h2a5f13c8b90d4e7;
        mask   = {DEG{1'b0}} | 70'h13f0c5a29e6b8d1;
        #1;
        if (back !== red_in) begin
            bad = bad + 1;
            $display("MISMATCH unmask round trip: got %h want %h", back, red_in);
        end

        if (bad == 0)
            $display("PASS sllc encoder matches polynomial division on 24 words");
        else
            $display("FAIL %0d of 25 checks", bad);
        $finish;
    end
endmodule

`default_nettype wire
