// GENERATED by gen_sllc.py --tb - do not edit by hand.
//
// The SLLC encoder's area was quoted for five loops with no testbench behind it, in a
// project whose rule is that no area is quoted for a circuit that has not been
// exercised. The register is checked here against a software polynomial division over
// GF(2), on 24 random information words, and an injected fault must fail it.

`timescale 1ns/1ps
`default_nettype none

module tb_sllc;
    localparam K = 29, DEG = 98;
    reg clk = 0, rst_n = 0, en = 0, bit_in = 0;
    wire [DEG-1:0] parity;

    sllc127t21_encoder dut (.clk(clk), .rst_n(rst_n), .en(en), .bit_in(bit_in),
                        .parity(parity));

    always #5 clk = ~clk;

    reg [K-1:0]   words  [0:23];
    reg [DEG-1:0] want   [0:23];   // not `expect`, which is a keyword
    integer v, b, bad;

    // The unmask stage is a bare exclusive-or, so it is checked by identity rather than
    // by vector: unmasking with the same mask must return the redundancy.
    reg  [DEG-1:0] red_in, mask;
    wire [DEG-1:0] helper, back;
    sllc127t21_unmask mk (.helper(red_in), .mask_noisy(mask), .redundancy(helper));
    sllc127t21_unmask um (.helper(helper), .mask_noisy(mask), .redundancy(back));

    initial begin
        words[0] = 29'h08a8e6a5; want[0] = 98'h176ae62900a3050975c950381;
        words[1] = 29'h1998cd32; want[1] = 98'h02eba702f0ee17ace1fa180de;
        words[2] = 29'h18608bd4; want[2] = 98'h1f10f065aaf144384919dd320;
        words[3] = 29'h155e82e4; want[3] = 98'h0dc0e305760125e855b9126e0;
        words[4] = 29'h1c99aa7a; want[4] = 98'h2177cbdf3003b86001cba0be0;
        words[5] = 29'h13652a92; want[5] = 98'h1d9006d1a0811ec10c7de7c45;
        words[6] = 29'h06ea357a; want[6] = 98'h10148b0e2e84f245744f2a769;
        words[7] = 29'h1c543a89; want[7] = 98'h1c05ca9da2269f1ef8e0818b3;
        words[8] = 29'h06e61a02; want[8] = 98'h1f5c0e0328d6ea5513ce572e6;
        words[9] = 29'h130548c5; want[9] = 98'h1f761779e8c8596c14ad550b1;
        words[10] = 29'h1f4c48c8; want[10] = 98'h0255eebb1c33405709559e9a8;
        words[11] = 29'h0c66a701; want[11] = 98'h15df97c37388bfe649ddafe4b;
        words[12] = 29'h168fe52b; want[12] = 98'h08000abfcafa31c08a28e504e;
        words[13] = 29'h13daee49; want[13] = 98'h1842cd3320e519d8d5761b81f;
        words[14] = 29'h07bb6a53; want[14] = 98'h00b236ca29132839207b51df3;
        words[15] = 29'h0cce76d1; want[15] = 98'h1bc0234033b63623a802127c3;
        words[16] = 29'h148e9bca; want[16] = 98'h35012038a9bd9e4a295e42ee3;
        words[17] = 29'h0cb33379; want[17] = 98'h38dfd22f2c4c67e75f28d7e50;
        words[18] = 29'h0b38a725; want[18] = 98'h2357f065e7b7e240ad56a4b88;
        words[19] = 29'h152e9d4c; want[19] = 98'h190ecb2af0f3116777471c28e;
        words[20] = 29'h0a032a56; want[20] = 98'h277be2de3243d979983ee02d8;
        words[21] = 29'h1a2ba26e; want[21] = 98'h0a3a8a320c5becc342f3badf4;
        words[22] = 29'h1343e3e6; want[22] = 98'h30e3f32a8ac6598c5648033a1;
        words[23] = 29'h16d5566e; want[23] = 98'h125985be753bf8a572b696238;
        bad = 0;
        for (v = 0; v < 24; v = v + 1) begin
            @(negedge clk); rst_n = 0; en = 0;
            @(negedge clk); rst_n = 1;
            for (b = K - 1; b >= 0; b = b - 1) begin
                bit_in = words[v][b];
                en = 1;
                @(negedge clk);
            end
            en = 0;
            if (parity !== want[v]) begin
                bad = bad + 1;
                $display("MISMATCH vector %0d: got %h want %h", v, parity, want[v]);
            end
        end

        red_in = {DEG{1'b0}} | 70'h2a5f13c8b90d4e7;
        mask   = {DEG{1'b0}} | 70'h13f0c5a29e6b8d1;
        #1;
        if (back !== red_in) begin
            bad = bad + 1;
            $display("MISMATCH unmask round trip: got %h want %h", back, red_in);
        end

        if (bad == 0)
            $display("PASS sllc encoder matches polynomial division on 24 words");
        else
            $display("FAIL %0d of 25 checks", bad);
        $finish;
    end
endmodule

`default_nettype wire
