#!/usr/bin/env python3
"""Every generated Verilog file must still match what its generator produces.

The decoders and masking stages in research/rtl are generated from (field, reduction,
correction strength) and then committed. Nothing checked that a committed file still
corresponds to the parameters its name claims. A file generated under one set and left
behind when the parameters moved would synthesise, decode, pass its testbench and be
wrong about which code it implements - and every check in this repository would stay
green, because they all measure the file rather than compare it to its source of truth.

That is the same class as W-INTL-212, one layer further out: there a measurement outlived
its operating point, here an artefact could outlive its parameters.

The file name carries the parameters. bch127t11_tables.v is GF(2^7) with t=11; sllc127t7.v
is the masking stage for t=7. Regenerate from the name and compare byte for byte.

Exit code 1 on any mismatch. Files whose header does not say GENERATED are skipped, and
the count of what was compared is printed, because a check that silently compares nothing
is the failure mode this project has met four times.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RTL = ROOT / "research" / "rtl"
POLY = {7: "0x09", 8: "0x1D", 9: "0x011"}


def parameters_from_name(name):
    """(generator, argv) implied by the file name, or None if it is not one of ours."""
    m = re.fullmatch(r"bch(\d+)(?:t(\d+))?_tables\.v", name)
    if m:
        n, t = int(m.group(1)), m.group(2)
        bits = {127: 7, 255: 8, 511: 9}.get(n)
        if bits is None:
            return None
        # The files without a t in the name are the two earliest, whose strength is in
        # their header rather than their name.
        return ("gen_bch_decoder.py", bits, t, name[:-len("_tables.v")])
    m = re.fullmatch(r"(tb_)?sllc(\d+)t(\d+)\.v", name)
    if m:
        n, t = int(m.group(2)), m.group(3)
        bits = {127: 7, 255: 8, 511: 9}.get(n)
        if bits is None:
            return None
        return ("gen_sllc.py", bits, t, f"sllc{n}t{t}", bool(m.group(1)))
    return None


def strength_from_header(path):
    m = re.search(r"t=(\d+)", path.read_text()[:600])
    return m.group(1) if m else None


def main():
    compared = 0
    failures = []

    for path in sorted(RTL.glob("*.v")):
        if "GENERATED by" not in path.read_text()[:400]:
            continue
        spec = parameters_from_name(path.name)
        if spec is None:
            failures.append(f"{path.name} says GENERATED and its name implies no "
                            f"parameters, so nothing can check it")
            continue

        if spec[0] == "gen_bch_decoder.py":
            _, bits, t, top = spec
            t = t or strength_from_header(path)
            if t is None:
                failures.append(f"{path.name}: cannot tell its correction strength")
                continue
            argv = [str(bits), POLY[bits], str(t), top]
        else:
            _, bits, t, top, is_tb = spec
            argv = [str(bits), POLY[bits], str(t), top] + (["--tb"] if is_tb else [])

        result = subprocess.run([sys.executable, spec[0], *argv],
                                capture_output=True, text=True, cwd=RTL)
        if result.returncode != 0:
            failures.append(f"{path.name}: generator failed")
            continue
        compared += 1
        if result.stdout != path.read_text():
            failures.append(f"{path.name} differs from what {spec[0]} produces for "
                            f"the parameters its name claims")

    for f in failures:
        print(f"FAIL: {f}")
    if failures:
        print(f"\ncheck_generated_rtl: {len(failures)} of {compared + len(failures)} "
              f"generated files do not match their generator")
        return 1
    if compared == 0:
        print("FAIL: no generated files compared, so this check read nothing")
        return 1
    print(f"check_generated_rtl: OK ({compared} generated files match their generator)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
