#!/usr/bin/env python3
"""Generate STATUS.md: what this work claims, what checks it, and what is still open.

Two hundred and twenty audit entries, ten checks, fifteen controls and a recommendation
that has moved four times. There has been no single place showing which of those are
closed, which are open, and which were named and deliberately not done - so a reader
arriving now has to reconstruct the state from a hundred-and-fifty-section research
document and a status table buried three thousand lines into an audit.

Generated rather than written, for the reason every generated thing here is generated: a
hand-written status page is a claim about the repository that nothing checks, and this
project has found six of those. `scripts/check_status_current.py` fails if the file on
disk differs from what this produces.

Usage: gen_status.py            writes STATUS.md
       gen_status.py --stdout   prints it
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AUDIT = ROOT / "audits" / "gc_intl_v2_weakness_audit_addendum.md"
OUT = ROOT / "STATUS.md"

OPEN_MARKERS = ("open", "named", "not done", "recorded, not changed")


def audit_rows():
    rows = []
    for line in AUDIT.read_text().splitlines():
        m = re.match(r"\| W-INTL-(\d+) \| (.+?) \|$", line)
        if m:
            rows.append((int(m.group(1)), m.group(2)))
    return rows


def checks():
    out = []
    for path in sorted((ROOT / "scripts").glob("check_*.py")):
        doc = path.read_text().split('"""')
        summary = doc[1].strip().splitlines()[0] if len(doc) > 1 else ""
        out.append((path.name, summary))
    return out


def controls():
    wf = (ROOT / ".github" / "workflows" / "hard-rules.yml").read_text()
    return len(re.findall(r"scripts/control\.py", wf)) - wf.count("--self-test")


def recommendation():
    r = subprocess.run([sys.executable, str(ROOT / "scripts" /
                                            "check_figures_reproduce.py")],
                       capture_output=True, text=True, cwd=ROOT)
    m = re.search(r"OK \((.+)\)", r.stdout)
    return m.group(1) if m else "not reproducible right now"


def render():
    rows = audit_rows()
    still_open = [(n, t) for n, t in rows
                  if any(t.lower().startswith(k) or f"; {k}" in t.lower()
                         for k in OPEN_MARKERS)]
    lines = []
    add = lines.append
    add("# Status")
    add("")
    add("Generated by `scripts/gen_status.py`. Do not edit: `check_status_current.py`")
    add("fails if this file and the generator disagree.")
    add("")
    add("## The recommendation")
    add("")
    add(f"{recommendation()}")
    add("")
    add("Every figure in that line is recomputed from `research/inputs.py` on each run.")
    add("")
    add("## Findings")
    add("")
    add(f"{len(rows)} entries in the weakness audit. {len(rows) - len(still_open)} "
        f"closed, {len(still_open)} open or deliberately deferred:")
    add("")
    # A row marked open whose own text names a higher-numbered entry has usually been
    # answered by it and never updated. Surfaced rather than silently counted as open,
    # because "open" in a status table that nobody revisits is the same failure as a note
    # nobody reads.
    def later_ref(n, text):
        return sorted({int(x) for x in re.findall(r"W-INTL-(\d+)", text) if int(x) > n})

    flagged = [(n, t, later_ref(n, t)) for n, t in sorted(still_open)]
    stale = [f for f in flagged if f[2]]
    add(f"Of those, {len(stale)} name a later entry in their own text and may have been "
        f"answered by it without the row being updated.")
    add("")
    add("| Entry | State | Later entry named |")
    add("|---|---|---|")
    for n, text, refs in flagged:
        marks = ", ".join(f"W-INTL-{r}" for r in refs) if refs else ""
        add(f"| W-INTL-{n} | {text} | {marks} |")
    add("")
    add("## Checks")
    add("")
    add(f"{len(checks())} checks, each with at least one control; {controls()} controls "
        f"run in CI.")
    add("")
    add("| Check | What it establishes |")
    add("|---|---|")
    for name, summary in checks():
        add(f"| `{name}` | {summary} |")
    add("")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render()
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
    else:
        OUT.write_text(text)
        print(f"gen_status: wrote {OUT.relative_to(ROOT)}")
